esphome:
  on_boot:
    then: 
    - lambda: |-
        ESP_LOGI("DEFAULTS ADDED", "Sensors and Settings Added");

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  passive_scan: true

# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name}
    password: !secret wifi_password
    

captive_portal:

# Enable Web server.
web_server:
  port: 80

# Time:
time:
  - platform: homeassistant
    id: homeassistant_time
  - platform: sntp
    id: sntp_time
    
# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: "${device_name} Version"
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: "${device_name} IP"
    ssid:
      name: "${device_name} SSID"
    bssid:
      name: "${device_name} BSSID"

#Various Other Sensors:
sensor:
  # Uptime sensor.
  - platform: uptime
    id: device_uptime
    name: "${device_name} Uptime"
    update_interval: 300s

# WiFi Signal sensor.
  - platform: wifi_signal
    id: wifi_dbm
    name: "${device_name} WiFi Signal"
    update_interval: 300s